import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return <>
    <section className="hero"><div className="wrap hero-inner"><div className="hero-copy"><div className="eyebrow light">TORDHER BITES • TORDHER, SWABI</div><h1>CRISPY.<br />JUICY.<br /><span>UNFORGETTABLE.</span></h1><p>Made fresh when you order. From signature burgers and golden broast to loaded meals built for sharing — your next craving starts here.</p><div className="hero-actions"><Link className="btn" href="/menu">Explore the Menu <span>→</span></Link><Link className="btn btn-light" href="/order/track">Track My Order</Link></div><div className="hero-points"><span>● Fresh to order</span><span>● Pickup & delivery</span><span>● Live tracking</span></div></div><div className="hero-art"><div className="burst"></div><Image className="hero-logo" src="/tordher-bites-logo.svg" alt="Tordher Bites" width={520} height={128} priority /><div className="hero-stamp">TORDHER<br /><b>SWABI</b></div></div></div></section>

    <section className="section"><div className="wrap"><div className="section-head"><div><div className="eyebrow">THE TORDHER BITES PROMISE</div><h2>Big flavour. Zero fuss.</h2><p className="section-sub">Fast ordering, fresh preparation and a clear view of your order from kitchen to collection.</p></div><Link className="btn btn-outline" href="/menu">Start an Order →</Link></div><div className="feature-grid"><article className="feature premium"><span className="feature-number">01</span><h3>Made after you order</h3><p>No sitting around. Your food enters the kitchen after checkout so it reaches you hot and crisp.</p></article><article className="feature premium"><span className="feature-number">02</span><h3>Your way, your timing</h3><p>Choose pickup or delivery, review everything clearly, and finish checkout without unnecessary steps.</p></article><article className="feature premium"><span className="feature-number">03</span><h3>Know what’s happening</h3><p>Follow Received, Preparing, Ready and Completed status without repeatedly calling the restaurant.</p></article></div></div></section>

    <section className="section section-dark"><div className="wrap split-callout"><div><div className="eyebrow light">BUILT FOR EVERY CRAVING</div><h2>One menu.<br />Plenty to love.</h2><p>Burgers with a proper crunch. Broast worth sharing. Shawarma, fries, drinks and family meals for the whole table.</p><Link className="btn" href="/menu">See What’s Cooking →</Link></div><div className="craving-stack"><div><b>Signature Burgers</b><span>Bold stacks, crispy chicken, serious satisfaction.</span></div><div><b>Golden Broast</b><span>Crunch outside. Tender inside. Made for sharing.</span></div><div><b>Meals & Sides</b><span>Easy favourites with fries, drinks and family value.</span></div></div></div></section>

    <section className="section section-soft"><div className="wrap final-cta"><div><div className="eyebrow">READY WHEN YOU ARE</div><h2>Turn the craving into an order.</h2><p className="section-sub">Pick your favourites, choose pickup or delivery, and let the kitchen take it from there.</p></div><div className="hero-actions"><Link className="btn" href="/menu">Order Now →</Link><Link className="btn btn-outline" href="/order/track">Track Existing Order</Link></div></div></section>
  </>
}
