'use client';
import {createContext,useContext,useEffect,useState} from 'react';

type Lang='en'|'ur'|'ps';
const C=createContext<{lang:Lang;setLang:(l:Lang)=>void}>({lang:'en',setLang:()=>{}});
const ur:Record<string,string>={
'Menu':'مینو','Track Order':'آرڈر ٹریک کریں','Order Now':'ابھی آرڈر کریں','Freshly prepared • Pickup & Delivery • Tordher, Swabi':'تازہ تیار • پک اپ اور ڈیلیوری • تورڈھیر، صوابی','Explore the Menu':'مینو دیکھیں','Track My Order':'میرا آرڈر ٹریک کریں','Fresh to order':'آرڈر پر تازہ','Pickup & delivery':'پک اپ اور ڈیلیوری','Live tracking':'لائیو ٹریکنگ','Big flavour. Zero fuss.':'بڑا ذائقہ، کوئی جھنجھٹ نہیں۔','Made after you order':'آپ کے آرڈر کے بعد تازہ تیاری','Your way, your timing':'آپ کی پسند، آپ کا وقت','Know what’s happening':'ہر مرحلے سے باخبر رہیں','Signature Burgers':'سگنیچر برگر','Golden Broast':'گولڈن بروسٹ','Meals & Sides':'میل اور سائیڈز','Order Now →':'ابھی آرڈر کریں →','Secure checkout':'محفوظ چیک آؤٹ','Finish Your Order':'اپنا آرڈر مکمل کریں','How would you like your order?':'آپ آرڈر کیسے لینا چاہتے ہیں؟','Pickup':'پک اپ','Delivery':'ڈیلیوری','Name':'نام','Phone':'فون','Delivery address':'ڈیلیوری ایڈریس','Order notes':'آرڈر نوٹس','Your order':'آپ کا آرڈر','Delivery fee':'ڈیلیوری فیس','Total':'کل','Place Order':'آرڈر کریں','Your Cart':'آپ کی ٹوکری','Subtotal':'ذیلی کل','Continue to Checkout →':'چیک آؤٹ جاری رکھیں →','Find your order':'اپنا آرڈر تلاش کریں','Track another order':'دوسرا آرڈر ٹریک کریں','Login':'لاگ اِن','Sign Up':'اکاؤنٹ بنائیں','Logout':'لاگ آؤٹ','Email':'ای میل','Password':'پاس ورڈ','Create Account':'اکاؤنٹ بنائیں','Welcome back':'خوش آمدید','Customer Login':'کسٹمر لاگ اِن','Full name':'پورا نام','Confirm password':'پاس ورڈ دوبارہ لکھیں','Already have an account?':'پہلے سے اکاؤنٹ ہے؟','New here?':'نئے ہیں؟'};
const ps:Record<string,string>={
'Menu':'مېنو','Track Order':'آرډر تعقیب کړئ','Order Now':'اوس آرډر وکړئ','Freshly prepared • Pickup & Delivery • Tordher, Swabi':'تازه تیار • پک اپ او ډیلیوري • تورډهېر، صوابۍ','Explore the Menu':'مېنو وګورئ','Track My Order':'زما آرډر تعقیب کړئ','Fresh to order':'د آرډر لپاره تازه','Pickup & delivery':'پک اپ او ډیلیوري','Live tracking':'ژوندی تعقیب','Big flavour. Zero fuss.':'لوی خوند، بې تکلیفه.','Made after you order':'ستاسو له آرډر وروسته تازه تیاری','Your way, your timing':'ستاسو خوښه، ستاسو وخت','Know what’s happening':'له هر پړاو خبر اوسئ','Signature Burgers':'ځانګړي برګرونه','Golden Broast':'ګولډن بروسټ','Meals & Sides':'میلونه او سایدز','Order Now →':'اوس آرډر وکړئ →','Secure checkout':'خوندي چیک آوټ','Finish Your Order':'خپل آرډر بشپړ کړئ','How would you like your order?':'خپل آرډر څنګه غواړئ؟','Pickup':'پک اپ','Delivery':'ډیلیوري','Name':'نوم','Phone':'فون','Delivery address':'د ډیلیورۍ پته','Order notes':'د آرډر یادښت','Your order':'ستاسو آرډر','Delivery fee':'د ډیلیورۍ فیس','Total':'ټول','Place Order':'آرډر وکړئ','Your Cart':'ستاسو ټوکرۍ','Subtotal':'فرعي ټول','Continue to Checkout →':'چیک آوټ ته دوام ورکړئ →','Find your order':'خپل آرډر ومومئ','Track another order':'بل آرډر تعقیب کړئ','Login':'ننوتل','Sign Up':'اکاؤنټ جوړ کړئ','Logout':'وتل','Email':'ایمیل','Password':'پاسورډ','Create Account':'اکاؤنټ جوړ کړئ','Welcome back':'ښه راغلاست','Customer Login':'د پیرودونکي ننوتل','Full name':'بشپړ نوم','Confirm password':'پاسورډ بیا ولیکئ','Already have an account?':'له مخکې اکاؤنټ لرئ؟','New here?':'نوي یاست؟'};
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLangState]=useState<Lang>('en');const setLang=(l:Lang)=>{setLangState(l);localStorage.setItem('tb_lang',l)};useEffect(()=>{const saved=localStorage.getItem('tb_lang') as Lang;if(saved&&['en','ur','ps'].includes(saved))setLangState(saved)},[]);useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ur'||lang==='ps'?'rtl':'ltr';const dict=lang==='ur'?ur:lang==='ps'?ps:{};const apply=()=>{document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n')||'';(el as HTMLElement).innerText=dict[key]||key})};apply();},[lang]);return <C.Provider value={{lang,setLang}}>{children}</C.Provider>}
export const useLanguage=()=>useContext(C);
export function LanguageSwitcher(){const {lang,setLang}=useLanguage();return <select className="lang-select" aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="en">English</option><option value="ur">اردو</option><option value="ps">پښتو</option></select>}
export function T({children}:{children:string}){const {lang}=useLanguage();const d=lang==='ur'?ur:lang==='ps'?ps:{};return <>{d[children]||children}</>}
