'use client';
import {use,useEffect,useState} from 'react';
import Link from 'next/link';
type O={orderNo:string;status:string;total:number;orderType:string;items:{name:string;qty:number;unitPrice:number}[]};
const baseStatuses=['Received','Preparing','Ready','Completed'];
const nice=(s:string)=>s==='OutForDelivery'?'Out for delivery':s;
export default function Order({params}:{params:Promise<{id:string}>}){const {id}=use(params);const [o,setO]=useState<O|null>(null),[err,setErr]=useState('');useEffect(()=>{const load=()=>fetch('/api/orders/'+encodeURIComponent(id)).then(async r=>{const d=await r.json();if(r.ok){setO(d);setErr('')}else setErr(d.error||'Order not found')}).catch(()=>setErr('Could not refresh order status'));load();const t=setInterval(load,5000);return()=>clearInterval(t)},[id]);const stages=o?.orderType==='Delivery'?['Received','Preparing','Ready','OutForDelivery','Completed']:baseStatuses;const index=o?stages.indexOf(o.status):-1;return <>
<section className="commerce-hero status-hero"><div className="wrap commerce-hero-inner"><div><div className="eyebrow light">CRISPY CORNER LIVE</div><h1>YOUR ORDER.<br/><span>IN MOTION.</span></h1><p>Kitchen progress appears here automatically every five seconds.</p></div><div className="commerce-hero-stat status-stat"><small>CURRENT STATUS</small><strong>{o?nice(o.status):'•••'}</strong><span>{o?.orderNo||'Loading order'}</span></div></div></section>
<main className="status-premium-section"><div className="wrap status-shell">{err?<div className="status-error"><div className="eyebrow">TRACKING ISSUE</div><h2>{err}</h2><p>Check your order number and try again.</p><Link href="/order/track" className="btn">Track another order</Link></div>:!o?<div className="status-loading"><span className="live-dot"></span><b>Connecting to the kitchen…</b></div>:<><div className="status-heading"><div><div className="eyebrow">LIVE ORDER #{o.orderNo}</div><h2>{o.status==='Received'?'Order confirmed.':nice(o.status)+'.'}</h2><p>{o.status==='Completed'?'Your order journey is complete. Enjoy your meal!':'We’ll keep this page updated while the kitchen works.'}</p></div><div className="auto-refresh"><span className="live-dot"></span> AUTO REFRESH • 5 SEC</div></div><div className="premium-progress">{stages.map((s,n)=><div className={'premium-step '+(n<index?'done':n===index?'current':'')} key={s}><div className="step-index">{n<index?'✓':String(n+1).padStart(2,'0')}</div><div><b>{nice(s)}</b><small>{n===index?'Current stage':n<index?'Completed':'Coming up'}</small></div></div>)}</div><div className="status-detail-grid"><section className="status-order-card"><div className="status-card-head"><div><small>YOUR ORDER</small><h3>{o.items.reduce((n,i)=>n+i.qty,0)} items</h3></div><strong>Rs {o.total}</strong></div><div className="status-lines">{o.items.map((i,n)=><div key={n}><span>{i.qty} × {i.name}</span><b>Rs {i.unitPrice*i.qty}</b></div>)}</div></section><aside className="status-meta-card"><small>FULFILMENT</small><h3>{o.orderType==='Pickup'?'Pickup':'Delivery'}</h3><p>{o.orderType==='Pickup'?'We’ll mark your order ready when it can be collected.':'Follow the status here as your order moves from kitchen to delivery.'}</p><Link href="/menu" className="text-action">Order something else →</Link></aside></div></>}</div></main>
</>}
