import { prisma } from '@/lib/prisma';
import { requireAdmin } from '@/lib/auth';
import { getCustomerSession } from '@/lib/customerAuth';
import { sendOrderConfirmation } from '@/lib/messaging';
import { z } from 'zod';
import { randomBytes } from 'crypto';

const orderSchema=z.object({customer:z.object({name:z.string().trim().min(2).max(80),phone:z.string().trim().regex(/^\+?[0-9][0-9\s()-]{8,19}$/),address:z.string().trim().max(300).optional().default('')}),type:z.enum(['Pickup','Delivery']),note:z.string().trim().max(300).optional().default(''),items:z.array(z.object({id:z.string().min(1),qty:z.number().int().min(1).max(50)})).min(1).max(50)}).superRefine((v,c)=>{if(v.type==='Delivery'&&!v.customer.address)c.addIssue({code:'custom',path:['customer','address'],message:'Address required'})});

export async function GET(){if(!(await requireAdmin()))return Response.json({error:'Unauthorized'},{status:401});const rows=await prisma.order.findMany({include:{items:true},orderBy:{createdAt:'desc'},take:200});return Response.json(rows.map(o=>({...o,id:o.id.toString(),items:o.items.map(i=>({...i,id:i.id.toString(),orderId:i.orderId.toString()}))})))}

export async function POST(req:Request){const parsed=orderSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return Response.json({error:'Please check order details',details:z.treeifyError(parsed.error)},{status:400});const data=parsed.data;try{const settings=await prisma.storeSetting.upsert({where:{id:1},update:{},create:{id:1}});if(!settings.isOpen)return Response.json({error:`Online ordering is currently closed. Hours: ${settings.openingTime}–${settings.closingTime}`},{status:409});const ids=[...new Set(data.items.map(i=>i.id))];const products=await prisma.product.findMany({where:{id:{in:ids},active:true}});if(products.length!==ids.length)return Response.json({error:'One or more menu items are unavailable'},{status:409});const map=new Map(products.map(p=>[p.id,p]));const subtotal=data.items.reduce((s,i)=>s+map.get(i.id)!.price*i.qty,0);if(data.type==='Delivery'&&subtotal<settings.minimumDelivery)return Response.json({error:`Minimum delivery order is Rs ${settings.minimumDelivery}`},{status:409});const deliveryFee=data.type==='Delivery'?settings.deliveryFee:0;const total=subtotal+deliveryFee;const orderNo=`TDB-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString('hex').toUpperCase()}`;const customerSession=await getCustomerSession();const order=await prisma.order.create({data:{orderNo,customerId:customerSession?.sub?String(customerSession.sub):null,customerName:data.customer.name,phone:data.customer.phone,address:data.customer.address||null,customerNote:data.note||null,orderType:data.type,total,deliveryFee,estimatedMinutes:settings.estimatedMinutes,items:{create:data.items.map(i=>{const p=map.get(i.id)!;return{productId:p.id,name:p.name,unitPrice:p.price,qty:i.qty}})}}});const origin=process.env.NEXT_PUBLIC_APP_URL||new URL(req.url).origin;void sendOrderConfirmation({orderNo,phone:order.phone,total,trackingUrl:`${origin}/order/${orderNo}`}).then(async result=>{if(result.sent)await prisma.order.update({where:{id:order.id},data:{messageSent:true}})}).catch(()=>{});return Response.json({orderNo,total,status:order.status,estimatedMinutes:order.estimatedMinutes},{status:201})}catch(error){console.error('Order creation failed:',error);return Response.json({error:'Could not place order. Please try again.'},{status:500})}}

export async function PATCH(req:Request){if(!(await requireAdmin()))return Response.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>null);const statuses=['Received','Preparing','Ready','OutForDelivery','Completed','Cancelled'];if(!body?.orderNo||!statuses.includes(body.status))return Response.json({error:'Invalid request'},{status:400});try{const order=await prisma.order.update({where:{orderNo:body.orderNo},data:{status:body.status}});return Response.json({orderNo:order.orderNo,status:order.status})}catch{return Response.json({error:'Order not found'},{status:404})}}
